version: "3.8"
services:
  postgres:
    image: postgres:17-alpine
    container_name: prompt-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prompt-manager-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
